#!/usr/bin/env bash

if [ $# != 1 ]; then
  echo "Usage: $(basename "$0") xx" >&2
  exit 1
fi

dir="day$1"
main="$dir/main.rb"

echo "Setting up $main"

mkdir $dir

cat <<EOF >> $main
#!/usr/bin/env ruby
# frozen_string_literal: true

require "pry-byebug"

def input
  @input ||= DATA.read
end

def part1
  raise NotImplementedError
end

def part2
  raise NotImplementedError
end

puts "Part 1: #{part1}"
puts "Part 2: #{part2}"

__END__
EOF

chmod +x $main
